name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build myapp_container
        run: docker build -t myapp_container ./myapp_container

      - name: Build mynginx_container
        run: docker build -t mynginx_container ./mynginx_container
